#!/bin/sh -e

case "$1" in
purge)
  rm -rf /var/lib/faker
  ;;

remove)
  [ -L /usr/bin/faker ] && rm -rf /usr/bin/faker

  for f in /usr/share/man/man1/faker-*.1.gz; do
    [ -L $f ] && rm -rf $f
  done
  [ -L /usr/share/man/man1/faker.1.gz ] && rm -rf /usr/share/man/man1/faker.1.gz

  [ -L /etc/bash_completion.d/faker ] && rm -rf /etc/bash_completion.d/faker
  [ -L /usr/share/zsh/site-functions/_faker ] && rm -rf /usr/share/zsh/site-functions/_faker
  [ -L /usr/local/share/zsh/site-functions/_faker ] && rm -rf /usr/local/share/zsh/site-functions/_faker
  ;;

upgrade | deconfigure)
  #
  ;;

abort-upgrade | failed-upgrade)
  # if [ -e "/etc/sudoers.pre-conffile" ]; then
  # mv /etc/sudoers.pre-conffile /etc/sudoers
  # fi
  ;;

*)
  echo "unknown argument --> $1" >&2
  exit 0
  ;;
esac
