Document: testpackage
Title: Debian testpackage Manual
Author: <insert document author here>
Abstract: This manual describes what testpackage is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/testpackage/testpackage.sgml.gz

Format: postscript
Files: /usr/share/doc/testpackage/testpackage.ps.gz

Format: text
Files: /usr/share/doc/testpackage/testpackage.text.gz

Format: HTML
Index: /usr/share/doc/testpackage/html/index.html
Files: /usr/share/doc/testpackage/html/*.html
